[global_task_arrangement]  # task参与的控制，注意⚠对于动态实物这些，必须要ctrl.toml开启之后（那里是管理轮询的总开关），才会生效
join_dyn_raffle = true
join_guard_raffle = true
join_storm_raffle = false
join_substance_raffle = true
join_tv_raffle = true
heartbeat = true
recv_heart_gift = true
open_silver_box = true
recv_daily_bag = true
sign = true
watch_tv = true
sign_fans_group = true
send_gift = true
exchange_silver_coin = true
judge_case = true
bili_main = true



[custom_task_arrangement]  # 与global_task_arrangement对应。针对某个具体用户的自定义(如果用户没有自定义的部分，就使用前面global那里的配置)
    [custom_task_arrangement.username]  # sub-table({'custom_task_arrangement': {'user0': {}, 'user1': {}}})，name与user.toml内的相同
    join_storm_raffle = true



[global_task_control]  # 具体的task细节控制，注意⚠必须要task_arrangement开启之后，才会生效
# 清理即将过期礼物，请true之后一定要把紧随其后的clean-expiring-gift2room设置为真实房间号
clean-expiring-gift = false
# 单位秒，这是控制定义过期礼物何时为“过期”的阈值
set-expiring-time = 0
# 对过期礼物是否优先投递到其他勋章(按照勋章等级由大到小顺序投递)，之后会剩余的清理掉至clean-expiring-gift2room
clean_expiring_gift2all_medal = false
clean-expiring-gift2room = 0

# 一天最多一个硬币兑换机会
silver2coin = false

# 自动投满佩戴勋章当日亲密度
send2wearing-medal = false
# 短房间号(与投满亲密度send2wearing-medal的一起使用)。注意⚠️如果只需要投佩戴的勋章，不用修改send2medal
send2medal = []

# 输入数字 0-5 表示主站每日自动投币
givecoin = 0
# av获取(bilitop或者uper)分别代表b站随机或者根据up主mid选取
fetchrule = "bilitop"
# up主list([123]或者[123, 234, 123]等)
mid = [ 207539637,]

# 抽奖@的人，格式为 uid = "用户名"（例如 {332704117 = "白上吹雪Official", 339567211 = "赤井心Official"}）
# 要求被@的人不能经常改名字，这样也就说明这些用户也可控，即不得随意骚扰他人
dyn_lottery_friends = {}



[custom_task_control]  # 与global_task_control对应。针对某个具体用户的自定义(如果用户没有自定义的部分，就使用前面global那里的配置)
    [custom_task_control.username]  # sub-table({'custom_task_control': {'user0': {}, 'user1': {}}})，name与user.toml内的相同
    givecoin = 5
    [custom_task_control."xxx.qq.com"]  # 用户名如果包含.这个特殊符号需要使用双引号括起来，这里xx.qq.com就是username
    givecoin = 5